{{- if eq .Values.pgwatch.postgres.create_metric_database "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: pgwatch-postgresql-secret-postgres
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: cG9zdGdyZXM=  
  password: YmVlRit1MWJvaGNlNXhpZVphYW1haENoZWkzdXRodT4= 

---
apiVersion: v1
kind: Secret
metadata:
  name: pgwatch-postgresql-secret-pgwatch
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: cGd3YXRjaA==   
  password: YXdhZXM2b2hSMWRlZTJpZWRvbzFuMEFvMmxpZTNMZS0=  
{{ end }}
